### PR TITLE
Accept array for Pane boxShadow and width

### PR DESCRIPTION
**Pull request by pvenable**
Arrays are sometimes passed for responsive styles.

[#170346559]

### CODE REVIEW

**Comment by euanlau** [comment]
would you like it to support the object style as well?

**Comment by pvenable** [comment]
Not sure if we have the use case, but I guess since you mention it maybe at this point we should just pull in https://www.npmjs.com/package/@styled-system/prop-types and use the exported `propType` from here rather than doing it manually: https://github.com/styled-system/styled-system/blob/master/packages/prop-types/src/index.js#L18-L23.

I'm not sure our prop types are in great shape overall at the moment.  What do you think about that solution?

**Comment by euanlau** [comment]
pulling in styled system seems reasonable

**Comment by pvenable** [comment]
Updated; what do you think @euanlau?

**Pull request merged**
